### ISSUE TITLE
generating timings

### ISSUE THREAD

**Issue by mandric** [guoyunhe/rabbit-lyrics#1]
Hi, thanks for this great library!  I was just curious if you used a tool to generate the timings for your lyrics/subtitle files or you did them manually?  I'm looking for a way to automate that if possible.  So far I found this: https://github.com/readbeyond/aeneas/.

**Comment by guoyunhe** [comment]
You need to type all timestamps manually. This library doesn't do anything like that. In browser environment, it is very hard to do this with JavaScript.
