### ISSUE TITLE
Initializing more than one lyrics for one audio/video

### ISSUE THREAD

**Issue by Emperyal** [guoyunhe/rabbit-lyrics#10]
First I’m so grateful for this useful plugin. I have a suggestion. It would be nice if we could synchronize the same media element with multiple lyrics at the same time. For instance, playing an audio file with two sets of lyrics in different languages, one a translation of the other. If it is possible, it will be appreciated.

**Comment by guoyunhe** [comment]
I will make a demo for it. Should be possible with a little change.

**Comment by Emperyal** [comment]
Hi @guoyunhe, 
I'm just posting to check how far the process goes. I look forward to your implementation.

**Comment by guoyunhe** [comment]
@Emperyal Check this example https://guoyunhe.github.io/rabbit-lyrics/#example-multiple-lyrics

You need to download the latest version from GitHub or NPM.

**Comment by Emperyal** [comment]
I tried the new version and saw that it works fine. Awesome! Thank you for your efforts.
