### ISSUE TITLE
Error timestamp with hours [hh:mm:ss.xx]

### ISSUE THREAD

**Issue by phuong44dltt** [guoyunhe/rabbit-lyrics#12]
In release 1.1.0, I see : Support timestamp with hours [hh:mm:ss.xx], like [2:17:53.92].

But It's not work.

Please help me.

My audio http://www.hoasentrenda.org/Audio/AnhTri/Utah-2004.mp3

Thank you very much!

**Comment by guoyunhe** [comment]
Please share your code. Otherwise I cannot help.

**Comment by phuong44dltt** [comment]
My web htm here http://www.hoasentrenda.org/Audio/Lyrics/Utah-2004.htm
It play good from test1 to test4

And error test5, test6, test7, test8, test9, test10. 
test6, test7, test8, test9, test10 had code [hh:mm:ss.xx]

`        [00:00.14]  test1 Năm ông,  một ông phía trên .... Tất cả đều ở những cái ....  
        [00:06.33]  test2 Ông ở trên này, ổng dùng tâm chú của ổng
        [00:09.08]  test3 Năm ông dùng tâm chú...
        [00:10.67]  test4
        [00:13.69]  test5
        [1:13:11.01]  test6 Có một thằng nào đó nó sợ, đừng có sợ
        [1:13:14.03]  test7 Tội vậy hả.
        [1:13:15.50]  test8  
        [1:13:21.69]  test9
        [1:13:25.65]  test10`

**Comment by guoyunhe** [comment]
Please download the latest version. I fixed it. [link](https://raw.githubusercontent.com/guoyunhe/rabbit-lyrics/master/dist/rabbit-lyrics.js)

**Comment by phuong44dltt** [comment]
I use 
<script language="JavaScript" type="text/javascript" src="https://raw.githubusercontent.com/guoyunhe/rabbit-lyrics/master/dist/rabbit-lyrics.js"></script>
But it until not work with lager 1 hour.

  
**My code below**. You can use it to retest your code please. It until error from test6 to test10. But from test1 to test5, I test it is good.
------------------------------------------------------------------------------------------------------
<audio style="width:100%; height: 40px" id="audio-4" controls>

<source src="http://www.hoasentrenda.org/Audio/AnhTri/Utah-2004.mp3" type="audio/mpeg">
</audio>
<br />
<br />
 
<div class="rabbit-lyrics" data-media="#audio-4" data-view-mode="mini">
[00:00.14]  test1 Năm ông,  một ông phía trên .... Tất cả đều ở những cái ....
[00:06.33]  test2 Ông ở trên này, ổng dùng tâm chú của ổng
[00:09.08]  test3 Năm ông dùng tâm chú...
[00:10.67]  test4
[00:13.69]  test5
[1:13:11.01]  test6 Có một thằng nào đó nó sợ, đừng có sợ
[1:13:14.03]  test7 Tội vậy hả.
[1:13:15.50]  test8
[1:13:21.69]  test9
[1:13:25.65]  test10
</div>
-------------------------------------------------------

**Comment by guoyunhe** [comment]
You cannot use:
```html
<script language="JavaScript" type="text/javascript" 
src="https://raw.githubusercontent.com/guoyunhe/rabbit-lyrics/master/dist/rabbit-lyrics.js">
</script>
```

because github doesn't allow you to use it as remote JavaScript. You have to download it and upload to your web server.

**Comment by guoyunhe** [comment]
Working code is here:

https://codepen.io/guoyunhe/pen/eYOdzja

**Comment by phuong44dltt** [comment]
Thank you very much. It worked well.
