### ISSUE TITLE
Support for Changing the Lyrics?

### ISSUE THREAD

**Issue by adolhunter** [guoyunhe/rabbit-lyrics#17]
I tried to create a React app using this component; I noticed that on the first load, the component works perfectly. After that, however, even if the same text is supplied to the division, the lyrics display would not work. Is this the expected behavior? If so, is there anyway to modify the code to be able to change the lyrics and rerender using React?

**Comment by adolhunter** [comment]
That is, when I load the page for the first time, the component would work. After I change the lyrics inside the div tag, even if it is changing it to the exact same thing, the component would not work.

**Comment by adolhunter** [comment]
I actually was able to resolve this issue using the following code.

 _componentDidUpdate() {
        this.textRef.current.classList.remove("rabbit-lyrics");
    this.textRef.current.classList.remove("rabbit-lyrics--default");
    this.textRef.current.classList.remove("rabbit-lyrics--enabled");
    this.textRef.current.classList.remove("rabbit-lyrics--playing");
    new RabbitLyrics({
      element: this.textRef.current,
      mediaElement: this.mediaRef.current,
      height: 800,
    });
  }_

_textRef_ is my reference to the lyrics element. By removing these properties from classList, I was able to reuse the constructor on the lyrics text and make it work.

**Comment by nonoumasy** [comment]
I'm also trying to make this work with React. Is it possible to share your code. thanks.

**Comment by adolhunter** [comment]
@nonoumasy 
You can refer to this file as a working implementation. Note that this is pretty long ago so may not be the most elegant solution.
https://github.com/adolhunter/musicplayer/blob/master/src/RabbitPlayer.jsx

**Comment by nonoumasy** [comment]
@adolhunter . Thanks. I'm taking a look at your code now. 
Here is my project FYI:
https://nono-player.netlify.app/
