### ISSUE TITLE
Timestamps with hours, and fix vertical/horizontal size of lyrics frame

### ISSUE THREAD

**Issue by ivandonets** [guoyunhe/rabbit-lyrics#2]
Greetings, thanks for a wonderful library. never used any plugins for wordpress, but tryed your plugin and it worked immediately perfectly. however, one problem is there (or a few).

I want to use your player for (philosophical) lectures, audiobooks, so they can be longer than 99 minutes Is it supported now (longer than 99 minutes files?)?

Please take a look at what I am doing:
https://harekrishnalectures.000webhostapp.com/%D0%B4%D1%83%D1%88%D0%B0-%D1%87%D0%B0%D1%81%D1%82%D0%B8%D1%86%D0%B0-%D1%81%D0%BE%D0%B7%D0%BD%D0%B0%D0%BD%D0%B8%D1%8F

Also text is not precisely formatted. The "window" (frame) with text is too small vertically, and at same time it is too large horizontally (overlapping menu on the right) (how to fix it? is it to be done by settings of your plugin, or in wordpress site settings itself?)

Also, I saw on one site similar technology like yours, but there is a feature to click on the text in the transcript (lyrics), and audio position is automatically changed to match time of clicked text position.

Ideally I think size of text vertically should not become scrollable inside small frame. rather, just scrolling the page should be the way of scrolling, IMHO.

Is there a way to make a player wider? (So that scrolling is more precise)

**Comment by guoyunhe** [comment]
It is now supported in version 1.1.0.
