### ISSUE TITLE
Support for amplitude js 

### ISSUE THREAD

**Issue by Samuel-Momoh** [guoyunhe/rabbit-lyrics#22]
I try setting up rabbits lyrics js with my music player it not initializing, my player is power by amplitude js. Do you have functionality for amplitude js audio player

**Comment by guoyunhe** [comment]
You are probably using it in a wrong way. You should use [callbacks](https://521dimensions.com/open-source/amplitudejs/docs/configuration/callbacks.html) to initialize RabbitLyrics. I cannot help more because I am not familiar with amplitude.js. You can ask amplitude.js developers for more help.
