### ISSUE TITLE
How to specify or format for hours

### ISSUE THREAD

**Issue by passionate2023** [guoyunhe/rabbit-lyrics#36]
Hi,

How to specify or format for hours?

ex: 23:59:05  => 23 hours 59 minutes 05 seconds

I have an audio which goes until 23 hours. Please suggest.

Some audio goes until 8 hours

The example https://guoyunhe.github.io/rabbit-lyrics/#install shown is about minutes = > 03:27.19

Please advise

Thanks

**Comment by passionate2023** [comment]
Any help on this?

**Comment by guoyunhe** [comment]
Use `[23:59:05.00]`
