### ISSUE TITLE
Combine CJK and Latin font, adjust Latin font size but keep texts aligned

### ISSUE THREAD

**Issue by Kirchheim** [guoyunhe/rabbit-lyrics#39]
When using with two columns, left column Chinese and right column Latin script (here German), the size of the German text is too large. When adjusting the font size for the German text, however, the texts in the left and right columns do not align anymore.

![image](https://github.com/user-attachments/assets/577d3217-f45e-4f65-80d4-80b84fc913ec)

![image](https://github.com/user-attachments/assets/1bb30405-b860-44ae-af2e-729ceeb3ba96)

**Comment by guoyunhe** [comment]
Currently, RabbitLyrics can only align active line. It is impossible to align everything. You can control CSS line-height to improve the visual effect. For example, when you change German font size to 24px, set both line-height to 36px.
