### ISSUE TITLE
Add class to container based on status of song

### ISSUE THREAD

**Issue by ajien** [guoyunhe/rabbit-lyrics#4]
It would be nice if the lyric container will indicate if the player is currently playing a song, is paused, or is finished.

**Comment by guoyunhe** [comment]
It seems easy to implement. Will include this feature in next release.

**Comment by guoyunhe** [comment]
It is now supported in 1.1.0. Container has some classes of playing status https://github.com/guoyunhe/rabbit-lyrics#custom-styles
