### ISSUE TITLE
Text goes out of sync when skipping

### ISSUE THREAD

**Issue by Emperyal** [guoyunhe/rabbit-lyrics#5]
The plugin works well on short audio files. But I've noticed a problem while using it on long audio files : to fast forward or rewind audio causes synchronization issues. If you don't ever any skipping in timeline this doesn't happen. Is there any way to fix that issue?

**Comment by guoyunhe** [comment]
Hi @Emperyal , thanks for reporting the issue. Are you using the JavaScript package or WordPress plugin? Can you provide a URL of example?

**Comment by guoyunhe** [comment]
Hi @Emperyal , thanks for the information. I can reproduce the issue with your example, in both Firefox and Chromium. I will continue debugging it. It may take some time.

**Comment by guoyunhe** [comment]
Hi @Emperyal , one more question: what browser and operating system are you using?

**Comment by guoyunhe** [comment]
I managed to produce a solution. I transcoded the audiofile.mp3 to various format (OGG, MP3, WebM). Then the time synchronization is perfect no matter how I skip it. Tested in both Firefox and Chrome. I am afraid that MP3 file is generated by some recorder application and is not properly encoded. You can simply transcode the file to MP3 or OGG. You can do it with VLC or online with https://cloudconvert.com/

**Comment by Emperyal** [comment]
I'm using Firefox browser and Windows 10. Actually I had downloaded it from Youtube with a downloader software in mp3 format. Thanks for your interest. I will try this solution and report the result.

**Comment by Emperyal** [comment]
Great! I got the same result when I transcoded it to mp3 format and this time it worked smoothly. Many thanks for your help again.

**Comment by phuong44dltt** [comment]
I'm had a same problem. And I used OGG, it is ok, not error. Thank for support.
