### ISSUE TITLE
Rabbit Lyrics doesn't see the wrapped media

### ISSUE THREAD

**Issue by Emperyal** [guoyunhe/rabbit-lyrics#6]
First thanks for this useful plugin. I've encountered a trouble while applying it. Rabbit Lyrics finds duly media elements when they are naked. But when i wrap audio or video element in any tag such as a &lt;div&gt; it can't see them and so synchronization does not start. How can I overcome this problem?

**Comment by guoyunhe** [comment]
You can give an id to audio/video element:

```html
<audio id="audio-1" controls>
    <source src="audio-1.ogg" type="audio/ogg">
    <source src="audio-1.mp3" type="audio/mpeg">
</audio>

<div class="rabbit-lyrics" data-audio="#audio-1">
[00:05.00] This is a little song
[00:07.00] The song that nobody knows
...
</div>
```

**Comment by Emperyal** [comment]
I think my question isn't clear enough. I already did so. I gave audio element an id and then specified it in `data-audio` attribute to initialize lyrics. No problem so far. But the question is that it doesn't work when I wrap the audio or video in a `div` or any other html tag, as shown below:

<pre style="color:#000000;background:#ffffff;"><span style="color:#a65700; ">&lt;</span><span style="color:#800000; font-weight:bold; ">div</span><span style="color:#a65700; ">&gt;</span>
    <span style="color:#a65700; ">&lt;</span><span style="color:#800000; font-weight:bold; ">audio</span><span style="color:#274796; "> </span><span style="color:#074726; ">id</span><span style="color:#808030; ">=</span><span style="color:#0000e6; ">"audio-1"</span><span style="color:#274796; "> </span><span style="color:#074726; ">src</span><span style="color:#808030; ">=</span><span style="color:#0000e6; ">"audio-1.mp3"</span><span style="color:#274796; "> </span><span style="color:#074726; ">controls</span><span style="color:#a65700; ">&gt;</span><span style="color:#a65700; ">&lt;/</span><span style="color:#800000; font-weight:bold; ">audio</span><span style="color:#a65700; ">&gt;</span>
<span style="color:#a65700; ">&lt;/</span><span style="color:#800000; font-weight:bold; ">div</span><span style="color:#a65700; ">&gt;</span>

<span style="color:#a65700; ">&lt;</span><span style="color:#800000; font-weight:bold; ">div</span><span style="color:#274796; "> </span><span style="color:#074726; ">class</span><span style="color:#808030; ">=</span><span style="color:#0000e6; ">"rabbit-lyrics"</span><span style="color:#274796; "> </span><span style="color:#074726; ">data</span><span style="color:#274796; ">-audio</span><span style="color:#808030; ">=</span><span style="color:#0000e6; ">"#audio-1"</span><span style="color:#a65700; ">&gt;</span>
    [<span style="color:#008c00; ">00</span>:<span style="color:#008c00; ">05.00</span>] This is a little song 
    [<span style="color:#008c00; ">00</span>:<span style="color:#008c00; ">07.00</span>] The song that nobody knows 
    ...
<span style="color:#a65700; ">&lt;/</span><span style="color:#800000; font-weight:bold; ">div</span><span style="color:#a65700; ">&gt;</span> 
</pre>

**Comment by guoyunhe** [comment]
OK, I found the reason. I changed the property name from `data-audio` to `data-media` at some point. But I forgot to update the document... Sorry.

Can you try:

```html
<div>
    <audio id="audio-1" src="audio-1.mp3" controls></audio>
</div>

<div class="rabbit-lyrics" data-audio="#audio-1">
    [00:05.00] This is a little song 
    [00:07.00] The song that nobody knows 
    ...
</div>
```

**Comment by Emperyal** [comment]
I tried this, but unfornutanely changing `data-audio` attribute to `data-media` didn't help and the issue continues.

**Comment by Emperyal** [comment]
Thank you. This version has been really helpful.
