### ISSUE TITLE
I'm trying to get this to work by following the examples. but it isn't working

### ISSUE THREAD

**Issue by OnlineVagrant** [guoyunhe/rabbit-lyrics#7]
```
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <link href="path/to/rabbit-lyrics/dist/rabbit-lyrics.css" rel="stylesheet" type="text/css"/>
    <script src="path/to/rabbit-lyrics/dist/rabbit-lyrics.js" type="text/javascript"></script>
</head>
 <body>
     <audio id="audio-1" controls>
         <!-- <source src="audio-1.ogg" type="audio/ogg"> -->
         <source src="/recordings/o.mp3" type="audio/mpeg">
    </audio>

     <div class="rabbit-lyrics" data-media="#audio-1">
         [00:05.00] This is a little song
         [00:07.00] The song that nobody knows
     </div>

 </body>
 </html>

```

and In my app.js file server I added

`const RabbitLyrics = require("rabbit-lyrics/dist/rabbit-lyrics");`

The audio plays but the lyrics renders as html.

What am I doing wrong?

**Comment by guoyunhe** [comment]
Please upload the full example so I can help. Your description is unclear.

**Comment by OnlineVagrant** [comment]
Thank you for responding. By "upload the full example" do you mean for me upload the html file being severed as well as the server file? or do you mean to show you the example I'm following as well as to show  how it renders in the browser?

**Comment by OnlineVagrant** [comment]
Most likely I think you mean the file. I have created a simplified version of the code.
[rabbit-lyrics-test.zip](https://github.com/guoyunhe/rabbit-lyrics/files/2947795/rabbit-lyrics-test.zip)

Please take a look.

**Comment by guoyunhe** [comment]
You need to change:

```html
<link href="path/to/rabbit-lyrics/dist/rabbit-lyrics.css" rel="stylesheet" type="text/css"/>
<script src="path/to/rabbit-lyrics/dist/rabbit-lyrics.js" type="text/javascript"></script>
```

to the **actual** path to your node_modules folder. It depends on your server configuration. From what I have seen, your public folder doesn't expose node_modules. This is the project configuration issue.

I modified it a little big https://drive.google.com/file/d/13IeBTRKdmwwau8VatUL4gbHkC5ntqpeo/view?usp=sharing

If you are new to web development, use `F12` in Chrome/Firefox and in **Console** and **Network** tabs you can find useful debug information.

**Comment by OnlineVagrant** [comment]
No matter what I do I can't get the server running. I keep getting `ReferenceError: window is not defined` so   I can't inspect neither the **console** nor **network tabs**. I think you simply copied the **rabbit-lyrics** folder to the  **public** folder, so I tried linking to that but got the same error. I tried linking to the actual folders in the **node_modules** folder but still got the same error. Maybe I'm just to inexperience in web development to understand how this works :'(.

**Comment by guoyunhe** [comment]
Here is the first thing you need to know when doing Node.js development: Browser environment and Node environment is different. Your server side JavaScript should not use client side JavaScript (Rabbit Lyrics is a client side JavaScript package).

Remove this line from app.js

```js
const RabbitLyrics = require("rabbit-lyrics/dist/rabbit-lyrics");
```

I cannot help you to configure you project. I would suggest to NOT using any Node.js or other backend framework. Just use some static HTML.

**Comment by OnlineVagrant** [comment]
Thank you. Working with a static html file made it simple to understand and I figured out how to use it in my project.
