### ISSUE TITLE
Can not use js to initialize.

### ISSUE THREAD

**Issue by Nriver** [guoyunhe/rabbit-lyrics#8]
Can not use the following code in example:
```
new RabbitLyrics({
  element: document.findElementById("lyrics-1"),
  mediaElement: document.findElementById("audio-1")
});
```  

The browser console says: Uncaught ReferenceError: RabbitLyrics is not defined.
I'm using the js in dist folder. The compressed code does not have the RabbitLyrics class.

**Comment by guoyunhe** [comment]
Please upload your full source code or using codepen.io

**Comment by guoyunhe** [comment]
Lack further information

**Comment by acedigibits** [comment]
facing the same issue on https://unpkg.com/rabbit-lyrics@2.1.1/dist/rabbit-lyrics.umd.production.min.js . 

Code :
`<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<style>
		.rabbit-lyrics{height: 100px !important}
	</style>
</head>
<body>
	<audio id="audio-1" src="sounds/Ganesh Aarti.mp3" controls></audio><br>
	<div id="lyrics-1" data-media="#audio-1">
		[00:00.00] Shendur lal chadhayo achchha gajmukhko, 
		[00:03.00]dondil lal biraje sut gauriharko
		[00:06.00]Hath liye gudladdu sai survarko, 
		[00:09.00]mahima kahe na jay lagat hoo padko.
	</div>
	<script type="text/javascript" src="js/rabbit-lyrics.umd.production.min.js"></script>
	<script type="text/javascript">
		new RabbitLyrics({
    element: document.findElementById('lyrics-1'),
    mediaElement: document.findElementById('audio-1')
})
	</script>
</body>
</html>`
